/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class StatsCalulatorTest {
    StatsCalculator sc = new StatsCalculator();
    int[] nums = {5, 2, 9, 1, 7};

    @Test public void testMinimumUsingForLoop() {
        assertEquals(1, sc.minimumUsingForLoop(nums));
    }
    @Test public void testMaximumUsingLoop() {
        assertEquals(9, sc.maximumUsingForLoop(nums));
    }
    @Test public void testSumUsingForLoop() {
        assertEquals(24, sc.sumUsingForLoop(nums));
    }
    @Test public void testAverageUsingForLoop() {
        assertEquals(1, sc.minimumUsingStream(nums));
    }
    @Test public void testMinimumUsingStream() {
        assertEquals(1, sc.minimumUsingStream(nums));
    }
    @Test public void testMaximumUsingStream() {
        assertEquals(9, sc.maximumUsingStream(nums));
    }
    @Test public void testSumUsingStream() {
        assertEquals(4.8, sc.averageUsingStream(nums));
    }
}
